### ISSUE TITLE
(10783) TypeError: Cannot read property 'where' of undefined

### ISSUE THREAD

**Issue by Matt77CHE** [Sickboy78/ioBroker.sureflap#1]
Hallo;
Ich habe die folgende Fehlermeldung im Log: (10783) TypeError: Cannot read property 'where' of undefined

Zudem steht in den Datenpunkten von "since" der jeweiligen Tiere nichts - werden die Daten erst übernommen, wenn ein Tier durch die Klappe ging, oder sollten sie vom Hub übernommen werden?

All devices online & connection sind auf true

**Comment by Matt77CHE** [comment]
Nachtrag:
mittlerweile sind 2 Tiere durch die Klappe, bei den 2 Tieren steht nichts im Datenpunkt. auch "inside" wurde nicht aktualisiert....

**Comment by Sickboy78** [comment]
Hallo @Matt77CHE ,
normalerweise startet der Adapter bei einem TypeError neu, d.h. er aktualisiert auch die Datenpunkte (since) nicht.
Der Fehler hört sich an, als wenn die zurückgelieferten Daten nicht der erwarteten Struktur entsprechen.
Falls du dich etwas mit der Materie auskennst, kannst du dich mal auf https://surepetcare.io/ anmelden und mithilfe der Entwicklertools des Browsers (F12) den Request https://app.api.surehub.io/api/me/start raussuchen und die Antwort (Response) kopieren? Dann könnte ich schauen, wo die Daten abweichen.
Falls nicht, sag Bescheid, dann muss ich ein paar mehr debug-Ausgaben einbauen, um dem Problem auf die Spur zu kommen.
VG

**Comment by Matt77CHE** [comment]
Guten Morgen @Sickboy78 ;
Das mit F12 habe ich bei einem anderen Adapter auch schon einmal machen müssen -  Ich habe es hier auch versucht, bräuchte jedoch noch ein paar Erläuterungen mehr, da ich nicht so der crack bin.... ich habe die Konsole geöffnet; > jedoch wo finde ich den Request  https://app.api.surehub.io/api/me/start ?

Kann sein, dass ich mich jetzt vollkommen ins Aus schmeisse, aber ich habe die Request URL  einfachmal ausgeführt, und dies erhalten: {"error":{"message":["Token not provided"]}}

(auf der surepetcare.io - Homepage habe ich mich eingeloggt...)

Ich habe schon zu Beginn auf der Startseite des Adapters eine Fehlermeldung:

![Adapter Sureflap](https://user-images.githubusercontent.com/73795309/111060142-0d211000-849b-11eb-8d4f-29f934d91cb2.jpg)

**Comment by Matt77CHE** [comment]
Ich glaub ich habs!
> ich habe mal eine zweite web Instanz installiert, da ich mich fragte, ob es ein Problem sein könnte, da die Adresse von dir gegeben https ist, meine web Instanz jedoch mit http läuft - so habe ich eine zweite, mit https installiert - und läuft!
habe nun alle daten :-)

**Comment by Sickboy78** [comment]
Hallo @Matt77CHE ,

freut mich, dass es nun funktioniert!

Allerdings würde ich gern verstehen, wo das Problem lag.
Mit web Instanz meinst du den web server Adapter (iobroker.web) oder den admin Adapter (iobroker.admin)?
Eigentlich sind alle Aufrufe meines Adapters an die Surepet Api mit https, unabhängig vom web oder admin adapter.
Ich habe bei mir web + admin Adapter mal auf http umgestellt, konnte jedoch den von dir beschriebenen Fehler nicht nachstellen ...
Komisch ist auch, dass du schon auf der Konfigurationsseite einen Fehler bekommst. Könntest du mir da mal die Konsolen-Ausgabe des Browser kopieren?

VG

**Comment by Matt77CHE** [comment]
Also mit dem web Adapter meinte ich den:

![web](https://user-images.githubusercontent.com/73795309/111069901-8f2b2c00-84cf-11eb-9081-376febb0c63f.JPG)

web.0 > http
web.1 > https

Komischerweise funktioniert es jetzt auch, wenn ich den web.1 (https) deaktiviere....

Hier die Kopie aus der Konsole:
(hab es als quote eingefügt, da es mir als code unübersichtlich vorkam - falls gewünscht, kann ich es auch noch als code einfügen)

> :8081/#tab-instances/config/system.adapter.sureflap.0:1 Autofocus processing was blocked because a document's URL has a fragment '#tab-instances/config/system.adapter.sureflap.0'.
VM1053 translate.js:24 "username": {"en": "username", "de": "username", "ru": "username", "pt": "username", "nl": "username", "fr": "username", "es": "username", "pl": "username", "it": "username", "zh-cn": "username"},
VM1053 translate.js:24 "password": {"en": "password", "de": "password", "ru": "password", "pt": "password", "nl": "password", "fr": "password", "es": "password", "pl": "password", "it": "password", "zh-cn": "password"},
adminConfig.js:17 nochange
adminConfig.js:24 Unknown event: nochange
VM1051 jquery-3.2.1.min.js:4 Refused to set unsafe header "Host"
send @ VM1051 jquery-3.2.1.min.js:4
ajax @ VM1051 jquery-3.2.1.min.js:4
(anonymous) @ index_m.html?0:235
httpRequest @ index_m.html?0:234
(anonymous) @ index_m.html?0:167
doLoginViaApi @ index_m.html?0:164
doLogin @ index_m.html?0:150
testLogin @ index_m.html?0:143
loadHelper @ index_m.html?0:92
(anonymous) @ index_m.html?0:61
r.onack @ VM1052 socket.io.js:8
r.onpacket @ VM1052 socket.io.js:8
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.ondecoded @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
a.add @ VM1052 socket.io.js:6
r.ondata @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:6
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:7
r.onData @ VM1052 socket.io.js:7
ws.onmessage @ VM1052 socket.io.js:8
VM1051 jquery-3.2.1.min.js:4 Refused to set unsafe header "Referer"
send @ VM1051 jquery-3.2.1.min.js:4
ajax @ VM1051 jquery-3.2.1.min.js:4
(anonymous) @ index_m.html?0:235
httpRequest @ index_m.html?0:234
(anonymous) @ index_m.html?0:167
doLoginViaApi @ index_m.html?0:164
doLogin @ index_m.html?0:150
testLogin @ index_m.html?0:143
loadHelper @ index_m.html?0:92
(anonymous) @ index_m.html?0:61
r.onack @ VM1052 socket.io.js:8
r.onpacket @ VM1052 socket.io.js:8
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.ondecoded @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
a.add @ VM1052 socket.io.js:6
r.ondata @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:6
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:7
r.onData @ VM1052 socket.io.js:7
ws.onmessage @ VM1052 socket.io.js:8
VM1051 jquery-3.2.1.min.js:4 Refused to set unsafe header "Origin"
send @ VM1051 jquery-3.2.1.min.js:4
ajax @ VM1051 jquery-3.2.1.min.js:4
(anonymous) @ index_m.html?0:235
httpRequest @ index_m.html?0:234
(anonymous) @ index_m.html?0:167
doLoginViaApi @ index_m.html?0:164
doLogin @ index_m.html?0:150
testLogin @ index_m.html?0:143
loadHelper @ index_m.html?0:92
(anonymous) @ index_m.html?0:61
r.onack @ VM1052 socket.io.js:8
r.onpacket @ VM1052 socket.io.js:8
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.ondecoded @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
a.add @ VM1052 socket.io.js:6
r.ondata @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:6
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:7
r.onData @ VM1052 socket.io.js:7
ws.onmessage @ VM1052 socket.io.js:8
adminConfig.js:17 nochange
adminConfig.js:24 Unknown event: nochange
VM1051 jquery-3.2.1.min.js:4 Refused to set unsafe header "Host"
send @ VM1051 jquery-3.2.1.min.js:4
ajax @ VM1051 jquery-3.2.1.min.js:4
(anonymous) @ index_m.html?0:235
httpRequest @ index_m.html?0:234
(anonymous) @ index_m.html?0:187
getSurePetDataFromApi @ index_m.html?0:185
(anonymous) @ index_m.html?0:151
Promise.then (async)
doLogin @ index_m.html?0:151
testLogin @ index_m.html?0:143
loadHelper @ index_m.html?0:92
(anonymous) @ index_m.html?0:61
r.onack @ VM1052 socket.io.js:8
r.onpacket @ VM1052 socket.io.js:8
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.ondecoded @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
a.add @ VM1052 socket.io.js:6
r.ondata @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:6
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:7
r.onData @ VM1052 socket.io.js:7
ws.onmessage @ VM1052 socket.io.js:8
VM1051 jquery-3.2.1.min.js:4 Refused to set unsafe header "Referer"
send @ VM1051 jquery-3.2.1.min.js:4
ajax @ VM1051 jquery-3.2.1.min.js:4
(anonymous) @ index_m.html?0:235
httpRequest @ index_m.html?0:234
(anonymous) @ index_m.html?0:187
getSurePetDataFromApi @ index_m.html?0:185
(anonymous) @ index_m.html?0:151
Promise.then (async)
doLogin @ index_m.html?0:151
testLogin @ index_m.html?0:143
loadHelper @ index_m.html?0:92
(anonymous) @ index_m.html?0:61
r.onack @ VM1052 socket.io.js:8
r.onpacket @ VM1052 socket.io.js:8
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.ondecoded @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
a.add @ VM1052 socket.io.js:6
r.ondata @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:6
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:7
r.onData @ VM1052 socket.io.js:7
ws.onmessage @ VM1052 socket.io.js:8
VM1051 jquery-3.2.1.min.js:4 Refused to set unsafe header "Origin"
send @ VM1051 jquery-3.2.1.min.js:4
ajax @ VM1051 jquery-3.2.1.min.js:4
(anonymous) @ index_m.html?0:235
httpRequest @ index_m.html?0:234
(anonymous) @ index_m.html?0:187
getSurePetDataFromApi @ index_m.html?0:185
(anonymous) @ index_m.html?0:151
Promise.then (async)
doLogin @ index_m.html?0:151
testLogin @ index_m.html?0:143
loadHelper @ index_m.html?0:92
(anonymous) @ index_m.html?0:61
r.onack @ VM1052 socket.io.js:8
r.onpacket @ VM1052 socket.io.js:8
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.ondecoded @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
a.add @ VM1052 socket.io.js:6
r.ondata @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:8
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:6
(anonymous) @ VM1052 socket.io.js:6
r.emit @ VM1052 socket.io.js:6
r.onPacket @ VM1052 socket.io.js:7
r.onData @ VM1052 socket.io.js:7
ws.onmessage @ VM1052 socket.io.js:8
admin.js:153 Cannot compare "" and "1.0.0"
upToDate @ admin.js:153
(anonymous) @ adminAdapters.js:1417
(anonymous) @ adminAdapters.js:672
(anonymous) @ adminAdapters.js:672
setTimeout (async)
(anonymous) @ adminAdapters.js:671
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
adminInstances.js:1065 152

**Comment by Sickboy78** [comment]
Hallo @Matt77CHE ,

danke für die Consolenausgabe, da war jetzt nichts ungewöhnliches dabei, war aber auch zu erwarten, wenns jetzt bei dir funktioniert.
Ich kanns mir immer noch nicht wirklich erklären, wo der Fehler herkam.
Ich schließe das Issue. Sollten wieder Probleme auftreten, mach einfach ein neues auf.

VG
