### ISSUE TITLE
Adapter startet nicht mehr

### ISSUE THREAD

**Issue by mharms1** [Sickboy78/ioBroker.sureflap#114]
Hallo,
der Adapter startet bei mir nicht mehr. Ich habe bereits die Obkjekte gelöscht und auch einen rollback zu einer älteren Version gemacht.

`
sureflap.1 | 2024-08-24 18:36:33.508 | error | Cannot read properties of undefined (reading 'message')
-- | -- | -- | --
sureflap.1 | 2024-08-24 18:36:33.507 | error | TypeError: Cannot read properties of undefined (reading 'message') at /opt/iobroker/node_modules/iobroker.sureflap/main.js:341:15 at runNextTicks (node:internal/process/task_queues:60:5) at process.processImmediate (node:internal/timers:454:9)
sureflap.1 | 2024-08-24 18:36:33.507 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'message')
sureflap.1 | 2024-08-24 18:36:33.506 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sureflap.1 | 2024-08-24 18:36:33.505 | error | creating device hierarchy failed.
`

Entweder ist es im Zusammenhang mit einem ioBroker Update oder es liegt daran, dass ich ein Haustier aus der App gelöscht habe.

**Comment by Sickboy78** [comment]
Hi,

ich vermute, dass es etwas mit dem gelöschten Tier zu tun hat.
Ich habe einige Log Ausgaben an den entsprechenden Stellen hinzugefügt.
Kannst du bitte die neueste Version direkt von github installiern, das Log Level auf silly stellen und die gesamte Ausgabe vom Start bis zum Fehler kopieren? Danke!

MfG

**Comment by mharms1** [comment]
Hi,
hast Du außer Log Ausgaben noch etwas anderes verändert? 
Mit der github Version startet der Adapter jetzt problemlos und alle Objekte werden auch angelegt.
Grüße und einen schönen Sonntag.

**Comment by mharms1** [comment]
Moin,
ach ok, verstanden. Hier kommen die Logs:

`
sureflap.1 | 2024-08-26 19:11:32.857 | debug | updating json event history with 10 events
-- | -- | -- | --
sureflap.1 | 2024-08-26 19:11:32.857 | debug | updating json event history for household 'MHome'
sureflap.1 | 2024-08-26 19:11:32.856 | debug | updating last movement for pet 'Whitey' with '{"last_direction":1,"last_flap":"SureFlap HWR","last_flap_id":675979,"last_time":"2024-08-26T04:54:43+00:00"}'
sureflap.1 | 2024-08-26 19:11:32.856 | debug | updating time outside for pet 'Whitey' with '{"count":4,"time_spent_outside":3576}'
sureflap.1 | 2024-08-26 19:11:32.854 | warn | history does not contain flap movement for pet 'Halsband_0113f05348'
sureflap.1 | 2024-08-26 19:11:32.854 | warn | aggregated report for pet 'Halsband_0113f05348' does not contain movement data
sureflap.1 | 2024-08-26 19:11:32.850 | debug | device hierarchy created.
sureflap.1 | 2024-08-26 19:11:32.773 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-08-26 19:11:32.621 | debug | searching and removing of deleted and renamed pets complete
sureflap.1 | 2024-08-26 19:11:32.558 | debug | deleted or renamed pet sureflap.1.MHome.HubPet.SureFlap_HWR.assigned_pets.Halsband_0113f05348 (Pet 'Halsband_0113f05348' (222257)) found. trying to delete
sureflap.1 | 2024-08-26 19:11:32.396 | debug | searching and removing of deleted and renamed pets
sureflap.1 | 2024-08-26 19:11:32.396 | debug | searching and removing of obsolete objects complete
sureflap.1 | 2024-08-26 19:11:32.359 | debug | deleting event history from adapter
sureflap.1 | 2024-08-26 19:11:32.358 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-08-26 19:11:32.354 | debug | searching and removing of obsolete objects
sureflap.1 | 2024-08-26 19:11:32.353 | debug | creating device hierarchy...
sureflap.1 | 2024-08-26 19:11:28.624 | info | update loop started
sureflap.1 | 2024-08-26 19:11:28.622 | info | starting update loop...
sureflap.1 | 2024-08-26 19:11:28.621 | info | connected
sureflap.1 | 2024-08-26 19:11:25.285 | debug | login count: 1
sureflap.1 | 2024-08-26 19:11:25.285 | debug | json: {"email_address":"mail@adresse","password":"******","device_id":"1050547954"}
sureflap.1 | 2024-08-26 19:11:25.285 | info | connecting...
sureflap.1 | 2024-08-26 19:11:25.284 | debug | starting SureFlap Adapter v2.2.1
sureflap.1 | 2024-08-26 19:11:25.283 | info | adapter configuration ok
sureflap.1 | 2024-08-26 19:11:25.283 | info | number of history entries: 10
sureflap.1 | 2024-08-26 19:11:25.283 | info | history enabled: false
sureflap.1 | 2024-08-26 19:11:25.283 | info | felaqua battery voltage empty: 5.2
sureflap.1 | 2024-08-26 19:11:25.282 | info | felaqua battery voltage full: 6.2
sureflap.1 | 2024-08-26 19:11:25.282 | info | surefeed battery voltage empty: 5.2
sureflap.1 | 2024-08-26 19:11:25.282 | info | surefeed battery voltage full: 6.2
sureflap.1 | 2024-08-26 19:11:25.282 | info | sureflap battery voltage empty: 5.1
sureflap.1 | 2024-08-26 19:11:25.281 | info | sureflap battery voltage full: 6.1
sureflap.1 | 2024-08-26 19:11:25.281 | info | API host: app-api.production.surehub.io
sureflap.1 | 2024-08-26 19:11:25.281 | info | checking adapter configuration...
sureflap.1 | 2024-08-26 19:11:25.264 | info | starting. Version 2.2.1 (non-npm: Sickboy78/ioBroker.sureflap) in /opt/iobroker/node_modules/iobroker.sureflap, node: v20.17.0, js-controller: 6.0.11
sureflap.1 | 2024-08-26 19:11:13.342 | info | terminating
sureflap.1 | 2024-08-26 19:11:12.840 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sureflap.1 | 2024-08-26 19:11:12.840 | info | terminating
sureflap.1 | 2024-08-26 19:11:12.839 | info | everything cleaned up
sureflap.1 | 2024-08-26 19:11:12.838 | info | Got terminate signal TERMINATE_YOURSELF
sureflap.1 | 2024-08-26 19:10:06.129 | debug | updating json event history with 10 events
sureflap.1 | 2024-08-26 19:10:06.129 | debug | updating json event history for household 'MHome'
sureflap.1 | 2024-08-26 19:10:06.128 | debug | updating last movement for pet 'Whitey' with '{"last_direction":1,"last_flap":"SureFlap HWR","last_flap_id":675979,"last_time":"2024-08-26T04:54:43+00:00"}'
sureflap.1 | 2024-08-26 19:10:06.128 | debug | updating time outside for pet 'Whitey' with '{"count":4,"time_spent_outside":3576}'
sureflap.1 | 2024-08-26 19:10:06.126 | warn | history does not contain flap movement for pet 'Halsband_0113f05348'
sureflap.1 | 2024-08-26 19:10:06.125 | warn | aggregated report for pet 'Halsband_0113f05348' does not contain movement data
sureflap.1 | 2024-08-26 19:10:06.120 | debug | device hierarchy created.
sureflap.1 | 2024-08-26 19:10:05.958 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-08-26 19:10:05.806 | debug | searching and removing of deleted and renamed pets complete
sureflap.1 | 2024-08-26 19:10:05.733 | debug | deleted or renamed pet sureflap.1.MHome.HubPet.SureFlap_HWR.assigned_pets.Halsband_0113f05348 (Pet 'Halsband_0113f05348' (222257)) found. trying to delete
sureflap.1 | 2024-08-26 19:10:05.502 | debug | searching and removing of deleted and renamed pets
sureflap.1 | 2024-08-26 19:10:05.501 | debug | searching and removing of obsolete objects complete
sureflap.1 | 2024-08-26 19:10:05.423 | debug | deleting event history from adapter
sureflap.1 | 2024-08-26 19:10:05.421 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-08-26 19:10:05.415 | debug | searching and removing of obsolete objects
sureflap.1 | 2024-08-26 19:10:05.414 | debug | creating device hierarchy...
sureflap.1 | 2024-08-26 19:10:01.712 | info | update loop started
sureflap.1 | 2024-08-26 19:10:01.710 | info | starting update loop...
sureflap.1 | 2024-08-26 19:10:01.710 | info | connected
sureflap.1 | 2024-08-26 19:09:58.374 | debug | login count: 1
sureflap.1 | 2024-08-26 19:09:58.374 | debug | json: {"email_address":"mail@adresse","password":"******","device_id":"1050547954"}
sureflap.1 | 2024-08-26 19:09:58.373 | info | connecting...
sureflap.1 | 2024-08-26 19:09:58.372 | debug | starting SureFlap Adapter v2.2.1
sureflap.1 | 2024-08-26 19:09:58.371 | info | adapter configuration ok
sureflap.1 | 2024-08-26 19:09:58.371 | info | number of history entries: 10
sureflap.1 | 2024-08-26 19:09:58.371 | info | history enabled: false
sureflap.1 | 2024-08-26 19:09:58.371 | info | felaqua battery voltage empty: 5.2
sureflap.1 | 2024-08-26 19:09:58.371 | info | felaqua battery voltage full: 6.2
sureflap.1 | 2024-08-26 19:09:58.370 | info | surefeed battery voltage empty: 5.2
sureflap.1 | 2024-08-26 19:09:58.370 | info | surefeed battery voltage full: 6.2
sureflap.1 | 2024-08-26 19:09:58.370 | info | sureflap battery voltage empty: 5.1
sureflap.1 | 2024-08-26 19:09:58.369 | info | sureflap battery voltage full: 6.1
sureflap.1 | 2024-08-26 19:09:58.369 | info | API host: app-api.production.surehub.io
sureflap.1 | 2024-08-26 19:09:58.369 | info | checking adapter configuration...
sureflap.1 | 2024-08-26 19:09:58.351 | info | starting. Version 2.2.1 (non-npm: Sickboy78/ioBroker.sureflap) in /opt/iobroker/node_modules/iobroker.sureflap, node: v20.17.0, js-controller: 6.0.11
sureflap.1 | 2024-08-26 19:09:58.080 | debug | States connected to redis: 0.0.0.0:9000
sureflap.1 | 2024-08-26 19:09:57.982 | debug | States create User PubSub Client
sureflap.1 | 2024-08-26 19:09:57.981 | debug | States create System PubSub Client
sureflap.1 | 2024-08-26 19:09:57.957 | debug | Redis States: Use Redis connection: 0.0.0.0:9000
sureflap.1 | 2024-08-26 19:09:57.881 | debug | Objects connected to redis: 0.0.0.0:9001
sureflap.1 | 2024-08-26 19:09:57.835 | debug | Objects client initialize lua scripts
sureflap.1 | 2024-08-26 19:09:57.686 | debug | Objects create User PubSub Client
sureflap.1 | 2024-08-26 19:09:57.685 | debug | Objects create System PubSub Client
sureflap.1 | 2024-08-26 19:09:57.683 | debug | Objects client ready ... initialize now
sureflap.1 | 2024-08-26 19:09:57.583 | debug | Redis Objects: Use Redis connection: 0.0.0.0:9001
sureflap.1 | 2024-08-26 19:09:52.834 | info | terminating
sureflap.1 | 2024-08-26 19:09:52.333 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sureflap.1 | 2024-08-26 19:09:52.332 | info | terminating
sureflap.1 | 2024-08-26 19:09:52.331 | info | everything cleaned up
sureflap.1 | 2024-08-26 19:09:52.330 | info | Got terminate signal TERMINATE_YOURSELF
sureflap.1 | 2024-08-26 18:38:39.187 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-08-26 18:38:38.824 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-08-26 18:38:35.222 | info | update loop started
sureflap.1 | 2024-08-26 18:38:35.221 | info | starting update loop...
sureflap.1 | 2024-08-26 18:38:35.220 | info | connected
sureflap.1 | 2024-08-26 18:38:33.388 | info | connecting...
sureflap.1 | 2024-08-26 18:37:33.388 | info | disconnected
sureflap.1 | 2024-08-26 18:37:33.387 | info | update loop stopped
sureflap.1 | 2024-08-26 18:37:33.387 | error | Error: Request error: 'Error: read ECONNRESET'. Retrying in 60 seconds
`

**Comment by Sickboy78** [comment]
Hi,
danke für die Logs.

Zwei Dinge sind allerdings merkwürdig.
1. Die Meldungen deuten daraufhin, dass nicht der fehlende Haushalt, sondern der fehlende Name für das gelöschte Tier das Problem ist. Das tritt eigentlich nur auf, wenn ein Tier einem Gerät zugeordnet ist, aber nicht mehr in der Liste der Tiere zu finden ist. Das sollte eigentlich nicht auftreten und konnte ich auch nicht reproduzieren, wenn ich bei mir ein Tier lösche ...
2. Die Meldung "deleted or renamed pet sureflap.1.MHome.HubPet.SureFlap_HWR.assigned_pets.Halsband_xxxxxx (Pet 'Halsband_xxxxxx' (xx)) found. trying to delete" kommt 2x in den Logs. Eigentlich sollte die nur 1x vorkommen und dann sollte der Eintrag gelöscht sein und beim nächsten Start sollte die Meldung nicht mehr erscheinen.

Falls du Zeit und Lust hast, der Sache auf den Grund zu gehen, hätte ich ein paar Fragen:
Hast du nur ein Tier gelöscht? Oder auch eines hinzugefügt?
Hast du eine Katzenklappe oder eine Haustierklappe? Noch weitere Geräte?
Ist Halsband_xxxxxx das gelöschte Tier?
Ist der Eintrag sureflap.1.MHome.pets.Halsband_xxxxxx weiterhin im Adapter vorhanden?
Ist der Eintrag sureflap.1.MHome.HubPet.SureFlap_HWR.assigned_pets.Halsband_xxxxxx weiterhin im Adapter vorhanden?
Taucht das gelöschte Tier noch in der Liste der Tiere in der App auf?
Taucht das gelöschte Tier noch bei den der Klappe (oder einem anderen Gerät) zugeordneten Tieren in der App auf? (In der App "Produkte" auswählen, dann das Gerät und dann "Einstellungen".)

MfG

**Comment by mharms1** [comment]
Moin,
genau, ich habe nur 1 Tier gelöscht und dieses ist auch nicht mehr in der App sichtbar. Ebenfalls auch nicht mehr in den Objekten und auch nicht in den debug logs Deines Adapters.
Verblieben sind eine Katzenklappe, eine Haustierklappe, ein implantierter Chip + 1 Chip an einem Halsband. 
Die Haustierklappe habe ich seit gestern offline genommen, aber der Fehler existierte ja auch schon vorher.

**Comment by mharms1** [comment]
Moin,
korrekt, nach einem Neustart kommen die beiden Meldungen immer wieder neu ins debug log

**Comment by Sickboy78** [comment]
Hi,
SureFlap_HWR ist die Katzenklappe oder?
Was heisst "Haustierklappe habe ich seit gestern offline genommen"? Nur ausgeschaltet oder auch aus der App gelöscht?

Ich hab noch ein paar debug Ausgaben hinzugefügt.
Wär super, wenn du nochmal die neuste Version direkt von github installieren könntest und nochmal die Logs nach dem Start postest. Danke!
MfG

**Comment by mharms1** [comment]
Moin,
genau, SureFlap_HWR ist die Katzenklappe. Die Haustierklappe ist nur ausgeschaltet und nicht gelöscht. Es muss etwas mit der Haustierklappe zu tun haben. Ich habe diese jetzt wieder eingeschaltet und nun läuft der Adapter nicht mehr. Schalte ich sie aus, geht der Adapter wieder. Ich habe die ID's im Log nun mal drin gelassen. Ich hoffe, damit kann niemand etwas anfangen. Ansonsten bitte löschen.

`
sureflap.1 | 2024-09-01 12:21:32.705 | info | terminating
-- | -- | -- | --
sureflap.1 | 2024-09-01 12:21:32.201 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sureflap.1 | 2024-09-01 12:21:32.201 | info | terminating
sureflap.1 | 2024-09-01 12:21:32.200 | info | everything cleaned up
sureflap.1 | 2024-09-01 12:21:32.187 | error | undefined is not a valid state value
sureflap.1 | 2024-09-01 12:21:32.187 | error | Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common-db/build/cjs/lib/common/maybeCallback.js:36:13) at Sureflap._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:3851:48) at Sureflap.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:3820:17) at Sureflap.setBatteryStatusToAdapter (/opt/iobroker/node_modules/iobroker.sureflap/main.js:1476:9) at /opt/iobroker/node_modules/iobroker.sureflap/main.js:652:13 at new Promise (<anonymous>) at Sureflap.getDeviceStatusFromData (/opt/iobroker/node_modules/iobroker.sureflap/main.js:631:39) at /opt/iobroker/node_modules/iobroker.sureflap/main.js:337:21 at runNextTicks (node:internal/process/task_queues:60:5) at process.processImmediate (node:internal/timers:454:9)
sureflap.1 | 2024-09-01 12:21:32.186 | error | unhandled promise rejection: undefined is not a valid state value
sureflap.1 | 2024-09-01 12:21:32.185 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sureflap.1 | 2024-09-01 12:21:32.184 | debug | updating json event history with 10 events
sureflap.1 | 2024-09-01 12:21:32.184 | debug | updating json event history for household 'MyHome'
sureflap.1 | 2024-09-01 12:21:32.183 | debug | updating last movement for pet 'Whitey' with '{"last_direction":1,"last_flap":"SureFlap HWR","last_flap_id":675979,"last_time":"2024-09-01T05:53:16+00:00"}'
sureflap.1 | 2024-09-01 12:21:32.183 | debug | updating time outside for pet 'Whitey' with '{"count":8,"time_spent_outside":3481}'
sureflap.1 | 2024-09-01 12:21:32.181 | warn | history does not contain flap movement for pet 'Halsband_0113f05348'
sureflap.1 | 2024-09-01 12:21:32.181 | warn | aggregated report for pet 'Halsband_0113f05348' does not contain movement data
sureflap.1 | 2024-09-01 12:21:32.177 | debug | device hierarchy created.
sureflap.1 | 2024-09-01 12:21:32.036 | debug | pet flap 'PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned.
sureflap.1 | 2024-09-01 12:21:32.036 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-09-01 12:21:31.861 | debug | searching and removing of deleted and renamed pets complete
sureflap.1 | 2024-09-01 12:21:31.609 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.PetDoor_Heizung.assigned_pets.Whitey (Pet 'Whitey' ('423259')) found. trying to delete (state)
sureflap.1 | 2024-09-01 12:21:31.608 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.PetDoor_Heizung.assigned_pets.Halsband_0113f05348 (Pet 'Halsband_0113f05348' ('281492')) found. trying to delete (state)
sureflap.1 | 2024-09-01 12:21:31.608 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.SureFlap_HWR.assigned_pets.Halsband_0113f05348 (Pet 'Halsband_0113f05348' (222257)) found. trying to delete (channel)
sureflap.1 | 2024-09-01 12:21:31.498 | debug | searching and removing of deleted and renamed pets
sureflap.1 | 2024-09-01 12:21:31.497 | debug | searching and removing of obsolete objects complete
sureflap.1 | 2024-09-01 12:21:31.420 | debug | deleting event history from adapter
sureflap.1 | 2024-09-01 12:21:31.419 | debug | pet flap 'MyHome.HubPet.PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned.
sureflap.1 | 2024-09-01 12:21:31.418 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-09-01 12:21:31.415 | debug | searching and removing of obsolete objects
sureflap.1 | 2024-09-01 12:21:31.414 | debug | creating device hierarchy...
sureflap.1 | 2024-09-01 12:21:27.861 | info | update loop started
sureflap.1 | 2024-09-01 12:21:27.859 | info | starting update loop...
sureflap.1 | 2024-09-01 12:21:27.859 | info | connected
sureflap.1 | 2024-09-01 12:21:25.748 | debug | login count: 1
sureflap.1 | 2024-09-01 12:21:25.748 | debug | json: {"email_address":"xxx@xxxde","password":"******","device_id":"1050547954"}
sureflap.1 | 2024-09-01 12:21:25.748 | info | connecting...
sureflap.1 | 2024-09-01 12:21:25.747 | debug | starting SureFlap Adapter v2.2.1
`

**Comment by mharms1** [comment]
Nach mehrmaligem Neustart der Instanz läuft der Adapter nun wieder. Die Haustierklappe meldet aber noch 3 Tiere, obwohl es nur noch 2 gibt. Das wird wohl dann eher ein Bug auf Herstellerseite sein. Logs:

`
sureflap.1 | 2024-09-01 12:27:08.183 | debug | updating json event history with 10 events
-- | -- | -- | --
sureflap.1 | 2024-09-01 12:27:08.183 | debug | updating json event history for household 'MyHome'
sureflap.1 | 2024-09-01 12:27:08.183 | debug | updating last movement for pet 'Whitey' with '{"last_direction":1,"last_flap":"SureFlap HWR","last_flap_id":675979,"last_time":"2024-09-01T05:53:16+00:00"}'
sureflap.1 | 2024-09-01 12:27:08.182 | debug | updating time outside for pet 'Whitey' with '{"count":8,"time_spent_outside":3481}'
sureflap.1 | 2024-09-01 12:27:08.180 | warn | history does not contain flap movement for pet 'Halsband_0113f05348'
sureflap.1 | 2024-09-01 12:27:08.180 | warn | aggregated report for pet 'Halsband_0113f05348' does not contain movement data
sureflap.1 | 2024-09-01 12:27:08.175 | debug | device hierarchy created.
sureflap.1 | 2024-09-01 12:27:08.053 | debug | pet flap 'PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned.
sureflap.1 | 2024-09-01 12:27:08.053 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-09-01 12:27:07.901 | debug | searching and removing of deleted and renamed pets complete
sureflap.1 | 2024-09-01 12:27:07.700 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.PetDoor_Heizung.assigned_pets.Whitey (Pet 'Whitey' ('423259')) found. trying to delete (state)
sureflap.1 | 2024-09-01 12:27:07.700 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.PetDoor_Heizung.assigned_pets.Halsband_0113f05348 (Pet 'Halsband_0113f05348' ('281492')) found. trying to delete (state)
sureflap.1 | 2024-09-01 12:27:07.699 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.SureFlap_HWR.assigned_pets.Halsband_0113f05348 (Pet 'Halsband_0113f05348' (222257)) found. trying to delete (channel)
sureflap.1 | 2024-09-01 12:27:07.565 | debug | searching and removing of deleted and renamed pets
sureflap.1 | 2024-09-01 12:27:07.565 | debug | searching and removing of obsolete objects complete
sureflap.1 | 2024-09-01 12:27:07.500 | debug | deleting event history from adapter
sureflap.1 | 2024-09-01 12:27:07.499 | debug | pet flap 'MyHome.HubPet.PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned.
sureflap.1 | 2024-09-01 12:27:07.499 | warn | could not get pet name for pet id (276864)
sureflap.1 | 2024-09-01 12:27:07.496 | debug | searching and removing of obsolete objects
sureflap.1 | 2024-09-01 12:27:07.495 | debug | creating device hierarchy...
sureflap.1 | 2024-09-01 12:27:04.016 | info | update loop started
sureflap.1 | 2024-09-01 12:27:04.013 | info | starting update loop...
sureflap.1 | 2024-09-01 12:27:04.013 | info | connected
sureflap.1 | 2024-09-01 12:27:00.959 | debug | login count: 1
sureflap.1 | 2024-09-01 12:27:00.958 | debug | json: {"email_address":"xxx@xxx.de","password":"*****","device_id":"1050547954"}
sureflap.1 | 2024-09-01 12:27:00.958 | info | connecting...
sureflap.1 | 2024-09-01 12:27:00.955 | debug | starting SureFlap Adapter v2.2.1
`

**Comment by Sickboy78** [comment]
Hi,

danke fürs Ausprobieren und Logs zur Verfügung stellen!
Mit den IDs kann keiner was anfangen, nur drauf achten, dass keine persönlichen Daten enthalten sind (Email, Password).

Also der erste Fehler kam daher, dass als Batteriewert 'undefined' zurückgeliefert wurde. Hatte ich so auch noch nicht. Evtl. braucht es eine Weile, wenn die Klappe länger ausgeschaltet war, bis ein Spannungswert zur Verfügung steht. Hat mit der Klappe bzw. dem eigentlichen Problem nichts zu tun. In der neusten Version fang ich das ab und gebe stattdessen eine Warnung aus.

Die neue Debug-Ausgabe "pet flap 'MyHome.HubPet.PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned." bestätigt den Verdacht, dass der Haustierklappe weiterhin 3 Tiere zugeordnet sind, obwohl nur 2 Tiere im Haushalt existieren. Daher kann für das 3. Tier kein Name ermittelt werden, was zum ursprünglichen Issue geführt hat und in der neusten Version zu einer Warnung "could not get pet name for pet id (276864)" führt. Mehr kann ich an der Stelle auch nicht machen, da es sich hier um einen Bug bzw. Dateninkonsistenz auf Herstellerseite handelt.

Zu den "deleted or renamed pet ... found. trying to delete (...)" Meldungen hab ich noch einen Bug in meinem Code gefunden. Hier wurde an unterschiedlichen Stellen der Name unterschiedlich zusammengebaut (mal original Tiername mit pet id und mal Tiername ohne Sonderzeichen mit tag id). Das habe ich nun korrigiert und damit sollten diese Meldungen hoffentlich verschwinden.

Wenn du bitte noch ein weiteres Mal den Adapter aktualisieren könntest und prüfen, ob jetzt die "deleted or renamed pet ... found. trying to delete (...)" Meldungen spätestens nach dem 2. Neustart verschwunden sind, wäre ich dir sehr verbunden. Danke!

MfG

**Comment by mharms1** [comment]
Hallo, die Meldung "trying to delete" ist nun weg. Ich denke, damit sind wir nun ein ganzes Stück weiter und ich kann den Adapter wieder gut nutzen.

Danke Dir für Deine Mühe :-)

`
sureflap.1 | 2024-09-01 18:22:23.046 | debug | updating json event history with 10 events
-- | -- | -- | --
sureflap.1 | 2024-09-01 18:22:23.046 | debug | updating json event history for household 'MyHome'
sureflap.1 | 2024-09-01 18:22:23.045 | debug | updating last movement for pet 'Whitey' with '{"last_direction":2,"last_flap":"SureFlap HWR","last_flap_id":675979,"last_time":"2024-09-01T15:40:37+00:00"}'
sureflap.1 | 2024-09-01 18:22:23.045 | debug | updating time outside for pet 'Whitey' with '{"count":8,"time_spent_outside":3481}'
sureflap.1 | 2024-09-01 18:22:23.042 | warn | history does not contain flap movement for pet 'Halsband_0113f05348'
sureflap.1 | 2024-09-01 18:22:23.041 | warn | aggregated report for pet 'Halsband_0113f05348' does not contain movement data
sureflap.1 | 2024-09-01 18:22:23.035 | debug | device hierarchy created.
sureflap.1 | 2024-09-01 18:22:22.925 | debug | pet flap 'PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned.
sureflap.1 | 2024-09-01 18:22:22.925 | warn | could not find pet with pet tag id (276864)
sureflap.1 | 2024-09-01 18:22:22.775 | debug | searching and removing of deleted and renamed pets complete
sureflap.1 | 2024-09-01 18:22:22.647 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.PetDoor_Heizung.assigned_pets.Whitey (Pet 'Whitey' ('297736')) found. trying to delete (state)
sureflap.1 | 2024-09-01 18:22:22.646 | debug | deleted or renamed pet sureflap.1.MyHome.HubPet.PetDoor_Heizung.assigned_pets.Halsband_0113f05348 (Pet 'Halsband 0113f05348' ('222257')) found. trying to delete (state)
sureflap.1 | 2024-09-01 18:22:22.464 | debug | searching and removing of deleted and renamed pets
sureflap.1 | 2024-09-01 18:22:22.464 | debug | searching and removing of obsolete objects complete
sureflap.1 | 2024-09-01 18:22:22.398 | debug | deleting event history from adapter
sureflap.1 | 2024-09-01 18:22:22.397 | debug | pet flap 'MyHome.HubPet.PetDoor_Heizung' has 3 pets assigned and household has 2 pets assigned.
sureflap.1 | 2024-09-01 18:22:22.397 | warn | could not find pet with pet tag id (276864)
sureflap.1 | 2024-09-01 18:22:22.392 | debug | searching and removing of obsolete objects
sureflap.1 | 2024-09-01 18:22:22.391 | debug | creating device hierarchy...
sureflap.1 | 2024-09-01 18:22:18.431 | info | update loop started
sureflap.1 | 2024-09-01 18:22:18.430 | info | starting update loop...
sureflap.1 | 2024-09-01 18:22:18.429 | info | connected
sureflap.1 | 2024-09-01 18:22:15.381 | debug | login count: 1
sureflap.1 | 2024-09-01 18:22:15.380 | debug | json: {"email_address":"x@xxx.de","password":"******","device_id":"1050547954"}
sureflap.1 | 2024-09-01 18:22:15.380 | info | connecting...
sureflap.1 | 2024-09-01 18:22:15.379 | debug | starting SureFlap Adapter v2.2.1
`

**Comment by Sickboy78** [comment]
Ich danke dir für deine Unterstützung.
Der Adapter ist somit wieder etwas fehlerresistenter geworden.
Ich werde noch ein paar Updates machen und dann in den nächsten Tagen eine neue Version zusammenschrauben.

MfG
Sebastian
