### ISSUE TITLE
Weight for remaining food in bowl not written

### ISSUE THREAD

**Issue by Steffan68** [Sickboy78/ioBroker.sureflap#13]
**Describe the bug**  
The value for the weight of the remaining food in the bowls are not written.
The below mentioned objects, e.g.  "'Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_FeedElla.bowls.0" is existing

![image](https://user-images.githubusercontent.com/96392112/146689254-18f1c124-067d-405c-8748-ae5be4d05ce4.png)

Food Type & Target Weight are proper written.

**To Reproduce**  
The below mentioned log entry is written on every adapter restart

**Expected behavior**  
Weight of the remaining food written as value.

**Screenshots & Logfiles**  
021-12-19 20:53:04.369  - [33mwarn[39m: sureflap.0 (4225) got feeder remaining food data for object 'Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_FeedYoda.bowls.0' but object does not exist. This can happen if number of bowls is changed. Restart adapter. If warning persists, contact developer.
2021-12-19 20:53:04.369  - [33mwarn[39m: sureflap.0 (4225) got feeder remaining food data for object 'Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_FeedElla.bowls.0' but object does not exist. This can happen if number of bowls is changed. Restart adapter. If warning persists, contact developer.
2021-12-19 20:53:04.369  - [33mwarn[39m: sureflap.0 (4225) got feeder remaining food data for object 'Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_FeedLuna.bowls.0' but object does not exist. This can happen if number of bowls is changed. Restart adapter. If warning persists, contact developer.
2021-12-19 20:53:04.369  - [33mwarn[39m: sureflap.0 (4225) got feeder remaining food data for object 'Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_FeedLilli.bowls.0' but object does not exist. This can happen if number of bowls is changed. Restart adapter. If warning persists, contact developer.

**Versions:**  
2021-12-19 20:55:49.387  - [32minfo[39m: sureflap.0 (11059) starting. Version 1.0.8 in /opt/iobroker/node_modules/iobroker.sureflap, node: v14.18.2, js-controller: 3.3.21

Thanks for support
  Steffan

**Comment by Sickboy78** [comment]
Hi Steffan,

thx for reporting this bug.
I'll have a look at it, but it could take some time, I'm quite busy over Xmas.

You have 4 feeders, is that correct?

Regards
Sebastian

**Comment by Steffan68** [comment]
Hello Sebastian,

thanks for the quick feedback... take the time you need ... it is all free for us, so fully appreciate all the time and work you spend.
Yes, I have 4 Feeders and 1 Door attached to 1 Hub.

Merry x-mas
  Steffan

**Comment by Sickboy78** [comment]
Hi Steffan,

best wishes for the new year!

I think I found the bug and hopefully fixed it in may last [commit](https://github.com/Sickboy78/ioBroker.sureflap/commit/14d6d4ee6720267b814705b5b8e9a570363c0dba).
Can you please update to the lastest code from github an check if your problem is fixed?

Regards
Sebastian

**Comment by Steffan68** [comment]
Hello Sebastian,

also Happy New Year!

thump up! Error is gone and values are now reported ...
![image](https://user-images.githubusercontent.com/96392112/148693928-07da183d-5bd6-4fe8-bafc-536601fedc74.png)

Another short question ... I have not understood the setting for:
  sureflap.0.Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_KatzenKlappe.assigned_pets.Ella.control.type
which I can set to "2": "OUTDOOR PET" or "3": "INDOOR PET"
Independent which value i configure ... I see the following info in the log: "undefined is not a valid state value for id "sureflap.0.Eisfahrtstrasse.EG_EG_SurePetHub.EG_KU_KatzenKlappe.assigned_pets.Ella.control.type""
Can I protect Kitten which are not allowed to go out? I can't find a corresponding feature in the original App.

Thanks
  Steffan

**Comment by Sickboy78** [comment]
Hi Steffan,

I'm happy it works now. :)
Nice cat monitor btw!

As for the Outdoor/Indoor pet, the setting is a bit hidden in the app.
You have to select "Household" from the menu, scroll down, select the flap, click the right button (probably "access" in english) and then you can set it for every pet.

![grafik](https://user-images.githubusercontent.com/8673383/148694939-74e47e95-be17-408f-a41f-9b021e3935ec.png)

There's also an info icon which shows an explanation of the feature. In short, an indoor pet can not use this flap to go out (only in).

As for the error you get when changing the pet type, could you pls open a new issue? Then I will have a lokk at it.

Regards
Sebastian

**Comment by Steffan68** [comment]
Hello Sebastian,

looks like you have the "Katzenklappe" and I have the "Haustierklappe" (our two older ones are a little bit to big for the "Katzenklappe" ;-) ). My menue is different to yours, I do not have the option you showed above. Will reach out to the vendor why they make here a difference between the two doors. Specially for our young kidden it would be helpful to block individual animals.

Regards
  Steffan

**Comment by Steffan68** [comment]
Update: Justed looked on the website ... Looks liek you have the "[Dualscan](https://www.surepetcare.com/de-de/haustierklappen/dualscan-mikrochip-katzenklappe)" version.

**Comment by Sickboy78** [comment]
Hi Steffan,

thanks for the info. Your first comment is correct, second not.
The Dualscan is not smart, only the 2 Connect versions are.
I have the "Katzenklappe Connect".

But you are right, there are differences between the "Katzenklappe Connect" and the "Haustierklappe Connect".
One thing I found during implementation is, the cat flap allows multiple curfew times, while the pet flap only allows one.
Also the API is a little bit different between the two.
But I didnt know, that the indoor/outdoor pet was a feature only for the cat flap.
That explains, why you get an error, when you try to set it.
Unfortunately that means, I have to disable this feature for the pet flap, since it's not supported ...

Best Regards
Sebastian
