### ISSUE TITLE
State Offline

### ISSUE THREAD

**Issue by dirni** [Sickboy78/ioBroker.sureflap#15]
**Expected behavior**  
All my Devices are Offline State (False)
only the ONLINE States are incorrect all other Datapoints still work

**Screenshots & Logfiles**  

![screen](https://user-images.githubusercontent.com/6689521/148699908-90031062-0226-4c92-9ef8-715577751875.PNG)

**Versions:**  
 - Adapter version: 1.0.9
 - JS-Controller version: 3.3.22
 - Node version: v12.22.8
 - Operating system: IOBroker Raspberry

**Comment by Sickboy78** [comment]
Hi Dirni,
hows the online status in the app? (can be seen when you open the menu)
Regards

**Comment by dirni** [comment]
Thanks for your fast answer.
All Devices are Online in the app, but since this morning everything works again, can not say why.
If the problem occurs again, I'll try to recreate it and get back to you.

regards

**Comment by Sickboy78** [comment]
Ok, then I will close the issue for now.
Sometimes if the hub looses it's connection to the server, for wathever reason, then all devices connected to the hub are shown as offline. Perhaps something like this happened.
If the problem reapears, pls reopen an issue.
