### ISSUE TITLE
Water dispenser integration

### ISSUE THREAD

**Issue by TomasiDeveloping** [Sickboy78/ioBroker.sureflap#16]
First of all, thank you very much for the adapter. Works perfectly.
I have now bought the water dispenser.
Would it be possible to implement this also in the adapter ? Thanks in advance.

**Comment by Sickboy78** [comment]
Hi,

since I have to reverse engineer the API, it is quite complicated without owning the water dispenser myself.
So I can't promise, that it will be soon.

Best Regards
Sickboy

**Comment by TomasiDeveloping** [comment]
Hello
Thank you very much for the quick reply.
Yes also does not press :-)
Should I be able to help somehow, since I own the water dispenser let me know

**Comment by DrivesMeCrazy** [comment]
Hi Sickboy78,

I've a Fellaqua as well. Let me know if I can support like capture data or what ever.

Best Regards,
Stefan

**Comment by Sickboy78** [comment]
Good news, everyone!
I got my cat a Felaqua for her 3. birthday.
So expect an update soon.

**Comment by Sickboy78** [comment]
Version 1.1.4 now supports Felaqua.

**Comment by TomasiDeveloping** [comment]
Wow. Thanks for the quick implementation. I will update and test it tomorrow.
