### ISSUE TITLE
undefined control.type

### ISSUE THREAD

**Issue by Matt77CHE** [Sickboy78/ioBroker.sureflap#18]
Hallo
Musste heute die neuen Lizenzvereinbahrungen in der App annehmen und mein PW ändern; dabei ist mir im Adapter im Log folgendes aufgefallen: 
" undefined is not a valid state value for id "sureflap.0.Home.Home_Cat_Hub.Buero_neu.assigned_pets.Charlie.control.type" "

Diese Meldung ist bei allen drei Haustieren gekommen....
Meine Adapter-Version ist 1.1.0
Die App Version ist 3.1.15 auf Android

Gruss
Matt

**Comment by Sickboy78** [comment]
Hallo @Matt77CHE ,

Problem ist bekannt, ich muss nur Zeit finden, es zu beheben.

Mit Version 1.0.6 wurde die Möglichkeit eingeführt, für jedes Tier pro Klappe festzulegen, ob es ein Freigänger oder Wohnungstier ist. Wie sich herausgestellt hat, wird das Feature aber nur von der Katzenklappe und nicht von der Haustierklappe unterstützt, d.h. ich muss das Feature für die Haustierklappe wieder ausbauen.

Es sollte aber, abgesehen von der Log-Meldung, keine weiteren negativen Auswirkungen auf den Adapter haben.

VG
Sickboy

**Comment by Matt77CHE** [comment]
Ok, vielen Dank für die Infos - schade, dass SurePet da wieder einmal nur halbe Sachen macht...
