### ISSUE TITLE
Zeitangabe stimmt in Vis nicht mit Adapterangaben überein

### ISSUE THREAD

**Issue by Matt77CHE** [Sickboy78/ioBroker.sureflap#2]
Hallo @Sickboy78  - Ich bins noch einmal;
Ich habe in Vis eine Verknüpfung mit dem Datenpunkt "since" angelegt. Dabei ist mir aufgefallen, dass die Zeitangabe im Datenpunkt stimmt; in der Vis-Verknüpfung wird jedoch anstatt zB 19:00 18:00 angezeigt.

Im Datenpunkt steht: Sun Mar 14 2021 19:39:00 GMT+0100 (Mitteleuropäische Normalzeit)
In der Vis-Verknüpfung dann:  ![Zeitstempel](https://user-images.githubusercontent.com/73795309/111080524-28be0200-84ff-11eb-97fc-6a166b683602.JPG)

Hast du eine Idee woran das liegen könnte?

Ein weiteres Anliegen hätte ich noch zu diesem Zeit Stempel: ich habe es in der Vis nicht fertig gebracht, dass es mir das "+00:00" (GMT) nicht anzeigt (empfinde ich als unnötig). Die Trennung von Datum und Uhrzeit konnte ich realisieren, indem ich das "T" als Trennzeichen angegeben habe.

**Comment by Matt77CHE** [comment]
.. wenn ich den Zeit Stempel aus einem anderen Adapter anzeigen lasse, stimmt dort die Zeit überein...

**Comment by Sickboy78** [comment]
Hallo @Matt77CHE ,
die Anzeige ist technisch korrekt. 18 Uhr GMT entspricht 19 Uhr GMT+1. Die Surepet-Api verwendet GMT und liefert daher den Zeitstempel in GMT. ioBroker stellt sie dann korrekt in der lokalen Zeitzone GMT+1 dar (tatsächlich ist aber GMT im Datenpunkt hinterlegt). Du müsstest also Vis dazu bringen, ebenfalls die lokale Zeitzone bei der Anzeige zu benutzen. Da kann ich dir allerdings nicht weiterhelfen.

VG
