### ISSUE TITLE
Error setting states with js controller 4.0.12

### ISSUE THREAD

**Issue by Strobelix80** [Sickboy78/ioBroker.sureflap#22]
Tried this Adapter for the first time. Getting states from API works perfectly.
Setting states instead fails with these errors:

System: Linux
Adapter version: 1.1.0
js controller 4.0.12
NPM 14.19.0

Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined at Sureflap.getTagIndexForDeviceIndex (/opt/iobroker/node_modules/iobroker.sureflap/main.js:2077:61) at Sureflap.resetControlPetTypeToAdapter (/opt/iobroker/node_modules/iobroker.sureflap/main.js:1363:25) at /opt/iobroker/node_modules/iobroker.sureflap/main.js:717:10 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5)

unhandled promise rejection: Cannot read property 'length' of undefined

Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

changing pet type failed: Error: Request returned status code 500

**Comment by Sickboy78** [comment]
Hi @Strobelix80 ,

thx for reporting this bug.

Do you have a cat flap (smaller one) or a pet flap?
Is pet type the only state giving an error or are there other states too?

Best Regards

**Comment by Strobelix80** [comment]
Until yesterday i had the bigger petflap. From today i have the smaller catflap. Both have same issues

**Comment by Sickboy78** [comment]
I updated to js controller 4.0.14 but I could not reproduce the issue.
So I would need more information.
The error indictates, the tags object is undefined, which should be there.

Could you do me a favor and log into the surepet app with a browser, i.e. open "https://surepetcare.io/". Login and open the browsers developer tools. In the network tab look for the request "https://app.api.surehub.io/api/**me**/start" (not https://app.api.surehub.io/api/start) and open it's response. Under data/devices there should be your devices listed and they should have a tags array.
Here is a screenshot how it looks for me:
![grafik](https://user-images.githubusercontent.com/8673383/154843206-6308b8a4-3841-49fb-8ff6-4b4a3e369103.png)

If you could make a screenshot from your data or even better, copy me the json response, I could further investigate the issue.

Best Regards

**Comment by Strobelix80** [comment]
After deleting all states and restarting the adapter, all issues are gone!
As you mentioned it was a tag mismatch with both flaps. Catflap uses tagid for pettype, Petflap doesnt. I renamed the new catflap with same name as the old petflap which explains this mismatch.

**Comment by Sickboy78** [comment]
Good to hear it's working now!
