### ISSUE TITLE
Feature Request: support local cloud services

### ISSUE THREAD

**Issue by tetzlav** [Sickboy78/ioBroker.sureflap#25]
Im no friend of someone cloud services. And the PetCare services lags sometimes a bit.
So i found this relaly nice project: https://github.com/plambrechtsen/pethublocal/
Its a local service that is spoofing the cloud services of PetCare.

The sureflap adapter should compatible with this, or im wrong?

**Comment by Sickboy78** [comment]
It should be, I think, if it behaves exactly like the cloud service ...
But I'm not familiar with this project and how it works, so no guarantee.
