### ISSUE TITLE
Error: Request returned status code 401

### ISSUE THREAD

**Issue by mproper23** [Sickboy78/ioBroker.sureflap#3]
Hab mir auch mal die Version 1.0.4 installiert. Konfig passt, eswerden alle 3 Katzen angezeigt. Die Instanz bleibt Gelb mit der Meldung Verbunden mit Sureflap false. ImLog steht:
Error: Request returned status code 401

**Comment by Sickboy78** [comment]
Hallo @mproper23 ,

kannst du die Instanz bitte auf debug stellen und mir die letzten 10 bis 20 Zeilen vor der Fehlermeldung kopieren?

VG

**Comment by mproper23** [comment]
Hallo,

hier der Auszug: 
Hoffe es hilft

sureflap.0 | 2021-04-01 14:45:41.760 | info | (6328) connecting...
-- | -- | -- | --
sureflap.0 | 2021-04-01 14:45:31.760 | info | (6328) disconnected
sureflap.0 | 2021-04-01 14:45:31.759 | error | (6328) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:45:31.125 | debug | (6328) login count: 2
sureflap.0 | 2021-04-01 14:45:31.124 | info | (6328) connecting...
sureflap.0 | 2021-04-01 14:45:21.122 | info | (6328) disconnected
sureflap.0 | 2021-04-01 14:45:21.122 | error | (6328) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:45:20.277 | debug | (6328) login count: 1
sureflap.0 | 2021-04-01 14:45:20.276 | info | (6328) connecting...
sureflap.0 | 2021-04-01 14:45:20.250 | info | (6328) starting. Version 1.0.4 in C:/Program  Files/iobroker/SmartHome1/node_modules/iobroker.sureflap, node:  v10.17.0, js-controller: 3.2.16
sureflap.0 | 2021-04-01 14:45:20.059 | debug | (6328) statesDB connected
sureflap.0 | 2021-04-01 14:45:20.058 | debug | (6328) States connected to redis: 127.0.0.1:9900
sureflap.0 | 2021-04-01 14:45:20.049 | debug | (6328) States create User PubSub Client
sureflap.0 | 2021-04-01 14:45:20.048 | debug | (6328) States create System PubSub Client
sureflap.0 | 2021-04-01 14:45:20.027 | debug | (6328) Redis States: Use Redis connection: 127.0.0.1:9900
sureflap.0 | 2021-04-01 14:45:20.023 | debug | (6328) objectDB connected
sureflap.0 | 2021-04-01 14:45:19.997 | debug | (6328) Objects connected to redis: 127.0.0.1:9001
sureflap.0 | 2021-04-01 14:45:19.970 | debug | (6328) Objects client initialize lua scripts
sureflap.0 | 2021-04-01 14:45:19.969 | debug | (6328) Objects create User PubSub Client
sureflap.0 | 2021-04-01 14:45:19.965 | debug | (6328) Objects create System PubSub Client
sureflap.0 | 2021-04-01 14:45:19.957 | debug | (6328) Objects client ready ... initialize now
sureflap.0 | 2021-04-01 14:45:19.883 | debug | (6328) Redis Objects: Use Redis connection: 127.0.0.1:9001
sureflap.0 | 2021-04-01 14:45:08.542 | info | (7544) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sureflap.0 | 2021-04-01 14:45:08.540 | info | (7544) terminating
sureflap.0 | 2021-04-01 14:45:08.539 | info | (7544) everything cleaned up
sureflap.0 | 2021-04-01 14:45:08.536 | info | (7544) Got terminate signal TERMINATE_YOURSELF
sureflap.0 | 2021-04-01 14:45:06.398 | info | (7544) disconnected
sureflap.0 | 2021-04-01 14:45:06.397 | error | (7544) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:45:05.725 | debug | (7544) login count: 2
sureflap.0 | 2021-04-01 14:45:05.725 | info | (7544) connecting...
sureflap.0 | 2021-04-01 14:44:55.723 | info | (7544) disconnected
sureflap.0 | 2021-04-01 14:44:55.723 | error | (7544) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:44:54.877 | debug | (7544) login count: 1
sureflap.0 | 2021-04-01 14:44:54.877 | info | (7544) connecting...
sureflap.0 | 2021-04-01 14:44:54.858 | info | (7544) starting. Version 1.0.4 in C:/Program  Files/iobroker/SmartHome1/node_modules/iobroker.sureflap, node:  v10.17.0, js-controller: 3.2.16
sureflap.0 | 2021-04-01 14:44:54.744 | debug | (7544) statesDB connected
sureflap.0 | 2021-04-01 14:44:54.743 | debug | (7544) States connected to redis: 127.0.0.1:9900
sureflap.0 | 2021-04-01 14:44:54.735 | debug | (7544) States create User PubSub Client
sureflap.0 | 2021-04-01 14:44:54.734 | debug | (7544) States create System PubSub Client
sureflap.0 | 2021-04-01 14:44:54.725 | debug | (7544) Redis States: Use Redis connection: 127.0.0.1:9900
sureflap.0 | 2021-04-01 14:44:54.718 | debug | (7544) objectDB connected
sureflap.0 | 2021-04-01 14:44:54.703 | debug | (7544) Objects connected to redis: 127.0.0.1:9001
sureflap.0 | 2021-04-01 14:44:54.684 | debug | (7544) Objects client initialize lua scripts
sureflap.0 | 2021-04-01 14:44:54.683 | debug | (7544) Objects create User PubSub Client
sureflap.0 | 2021-04-01 14:44:54.682 | debug | (7544) Objects create System PubSub Client
sureflap.0 | 2021-04-01 14:44:54.615 | debug | (7544) Objects client ready ... initialize now
sureflap.0 | 2021-04-01 14:44:54.529 | debug | (7544) Redis Objects: Use Redis connection: 127.0.0.1:9001
sureflap.0 | 2021-04-01 14:44:49.564 | info | (4040) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sureflap.0 | 2021-04-01 14:44:49.562 | info | (4040) terminating
sureflap.0 | 2021-04-01 14:44:49.561 | info | (4040) everything cleaned up
sureflap.0 | 2021-04-01 14:44:49.558 | info | (4040) Got terminate signal TERMINATE_YOURSELF
sureflap.0 | 2021-04-01 14:44:40.434 | info | (4040) disconnected
sureflap.0 | 2021-04-01 14:44:40.434 | error | (4040) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:44:39.530 | info | (4040) connecting...
sureflap.0 | 2021-04-01 14:44:39.505 | info | (4040) starting. Version 1.0.4 in C:/Program  Files/iobroker/SmartHome1/node_modules/iobroker.sureflap, node:  v10.17.0, js-controller: 3.2.16
sureflap.0 | 2021-04-01 14:41:50.613 | info | (856) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
sureflap.0 | 2021-04-01 14:41:50.611 | info | (856) terminating
sureflap.0 | 2021-04-01 14:41:50.610 | info | (856) everything cleaned up
sureflap.0 | 2021-04-01 14:41:50.608 | info | (856) Got terminate signal TERMINATE_YOURSELF
sureflap.0 | 2021-04-01 14:41:44.626 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:41:44.625 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:41:44.038 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:41:34.037 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:41:34.036 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:41:33.466 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:41:23.465 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:41:23.464 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:41:22.897 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:41:12.895 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:41:12.894 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:41:12.319 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:41:02.318 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:41:02.317 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:41:01.531 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:40:51.530 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:40:51.530 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:40:50.967 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:40:40.966 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:40:40.965 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:40:40.375 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:40:30.374 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:40:30.373 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:40:29.718 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:40:19.717 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:40:19.716 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:40:19.118 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:40:09.117 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:40:09.116 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:40:08.365 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:39:58.365 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:39:58.364 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:39:57.554 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:39:47.554 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:39:47.553 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:39:46.965 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:39:36.965 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:39:36.964 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:39:36.356 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:39:26.355 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:39:26.354 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:39:25.646 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:39:15.644 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:39:15.644 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:39:14.955 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:39:04.954 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:39:04.953 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:39:04.378 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:38:54.377 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:38:54.377 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:38:53.630 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:38:43.628 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:38:43.627 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:38:43.055 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:38:33.054 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:38:33.053 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:38:32.392 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:38:22.391 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:38:22.390 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:38:21.745 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:38:11.744 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:38:11.743 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:38:11.122 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:38:01.121 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:38:01.121 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:38:00.414 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:37:50.412 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:37:50.412 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:37:49.613 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:37:39.613 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:37:39.612 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:37:39.030 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:37:29.030 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:37:29.029 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:37:28.444 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:37:18.443 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:37:18.442 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:37:17.865 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:37:07.865 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:37:07.864 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:37:07.285 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:36:57.284 | info | (856) disconnected
sureflap.0 | 2021-04-01 14:36:57.284 | error | (856) Error: Request returned status code 401
sureflap.0 | 2021-04-01 14:36:56.717 | info | (856) connecting...
sureflap.0 | 2021-04-01 14:36:46.717 | info | (856) disconnected

**Comment by Sickboy78** [comment]
Ok. 401 heißt Unauthorized und es tritt schon beim Login auf.
Das bedeutet normalerweise, dass Login oder Passwort falsch sind.
Aber du sagst in der Adapterkonfiguration nimmt er Login und Password und deine Katzen werden angezeigt?
Kannst du mir noch sagen, welche version dein Admin-Adapter hat?

VG

**Comment by mproper23** [comment]
Hallo. Genau meine Katzen werden nach dem drücken auf speichern Angezeigt. Admin adapter hat version 4.2.1. 

Danke für deine Mühen

Von meinem iPhone gesendet

**Comment by Sickboy78** [comment]
Werden die Katzen auch beim "Betreten" der Adapterkonfiguration angezeigt oder nur beim Speichern?

Bitte Adapter aktualiseren.
Ich habe weitere debug Ausgaben hinzugefügt:
email_address:
password:
json:
Bei den 3 bitte prüfen, ob deine Login-Daten korrekt angezeigt werden.

Dann sollte es noch
result:
und optional
error:
geben.
Das oder die letzten bitte mal kopieren.

**Comment by mproper23** [comment]
Hallo,

 

Katzen wurden beim betreten angezeigt. Habe jetzt das Update gemacht. Jetzt funktionierts.

Kann ich hiermit auch eine Sperrzeit pro Katze einstellen?

 

Danke und Gruss Andy

 

Von: Sebastian ***@***.*** 
Gesendet: Donnerstag, 1. April 2021 23:28
An: Sickboy78/ioBroker.sureflap ***@***.***>
Cc: mproper23 ***@***.***>; Mention ***@***.***>
Betreff: Re: [Sickboy78/ioBroker.sureflap] Error: Request returned status code 401 (#3)

 

Werden die Katzen auch beim "Betreten" der Adapterkonfiguration angezeigt oder nur beim Speichern?

Bitte Adapter aktualiseren.
Ich habe weitere debug Ausgaben hinzugefügt:
email_address:
password:
json:
Bei den 3 bitte prüfen, ob deine Login-Daten korrekt angezeigt werden.

Dann sollte es noch
result:
und optional
error:
geben.
Das oder die letzten bitte mal kopieren.

**Comment by Sickboy78** [comment]
Hallo @mproper23 ,

super, dass der Adapter nun fuktioniert.
Aber komisch, ich hab am Code nichts geändert, nur mehr debug Ausgaben hinzugefügt...

Nein Sperrzeit pro Katze ist nicht möglich, die Surepet-Api des Herstellers erlaubt nur Sperrzeiten pro Klappe festzulegen.

VG
