### ISSUE TITLE
Battery voltage / percentage

### ISSUE THREAD

**Issue by DoraDeu** [Sickboy78/ioBroker.sureflap#32]
I am not sure if this is an issue or a feature request.
I use rechargeable batteries (4 ) In my sureflap. The red light starts very early to signal a low battery status. When I ignore it the sureflap continues working properly for a couple of weeks.
I guess the reason why the red light starts flashing very early is that the voltage threshold is based on the voltage of zinc alkaline battery. As the voltage of rechargeable NiMh batteries are lower - even if they are fully charged - I think that the red light starts flashing earlier if NiMh batteries are used.
Right now the voltage is 5,0522 V and the battery percentage datapoint shows "0". However the sureflap is still working.
Is it possible to calculate the battery percentage value depending on the type of batteries that is used?

**Comment by Sickboy78** [comment]
Unfortunately there is no indication on what battery type is used. But I could make the voltage thresholds configurable. I'll think about it.

**Comment by Sickboy78** [comment]
With v1.1.6 voltage threshold values for full/empty can now be set per device type in the adapter configuration. Hope this helps.
