### ISSUE TITLE
FaceID

### ISSUE THREAD

**Issue by Peterich36** [Sickboy78/ioBroker.sureflap#36]
Hello Sebastian,
I have the idea of ​​pairing the cat flap with a FaceID camera and am wondering if I can leave the cat flap as it is and put my camera in between for extra security? Do you have an idea if this is possible? I wanted to write you a message but I can't find a contact.
Best regards
Patrick

**Comment by Sickboy78** [comment]
Hi!
Theorethically possible, but practically a call to the Surepet API takes some time, and needs more time to propagate to the hub and to the flap. So locking or unlocking the flap will not really happen in realtime. But you can try. My email is in the readme, if you have further questions.
Best Regards
