### ISSUE TITLE
Error: Request returned status code 403

### ISSUE THREAD

**Issue by heiner1976** [Sickboy78/ioBroker.sureflap#39]
**Describe the bug**  
seit ein paar Tagen aktualisieren sich meine Objekt nicht mher unes es gibt den Fehler:

Error: Request returned status code 403

**To Reproduce**  
Login ist richtig und ist mit "Login successfull" bestätigt

Log:
```
sureflap.0 | 2023-06-02 06:08:36.154 | info | disconnected
-- | -- | -- | --
sureflap.0 | 2023-06-02 06:08:36.153 | error | Error: Request returned status code 403
sureflap.0 | 2023-06-02 06:08:35.704 | info | connecting...


```

**Versions:**  
 Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
2159 MHz
Modell
AMD Turion(tm) II Neo N54L Dual-Core Processor
RAM
7.45 GB
System-Betriebszeit
35 T. 12:37:00
Node.js
v16.19.1 (Es gibt eine neuere Version: v16.20.0 - Empfohlene Version v18.16.0)
time
1685680760786
timeOffset
-120
Anzahl der Adapter
474
NPM
8.19.3
Datenträgergröße
24.48 GB
freier Festplattenspeicher
10.11 GB
Betriebszeit
34 T. 22:21:46
Aktive Instanzen
39
Weg
/opt/iobroker/
Hostname
iOBroker2022

**Comment by Sickboy78** [comment]
Issue was fixed yesterday.
Please update to adapter v1.1.8.
