### ISSUE TITLE
Futterautomat hinzufügen / das pet feeder

### ISSUE THREAD

**Issue by Ceel84** [Sickboy78/ioBroker.sureflap#4]
Hallo
Ist es möglich den Futterautomaten hinzuzufügen
https://www.surepetcare.com/de-de/futterungsgerte/microchip-pet-feeder-connec

Hello
Pls add the pet feeder
https://www.surepetcare.com/de-de/futterungsgerte/microchip-pet-feeder-connect

**Comment by Sickboy78** [comment]
Hallo,

ich hab leider keinen Feeder und ohne wirds schwierig zu programmieren.
Mal schauen was bei der Steuererklärung übrig bleibt, vielleicht kauf ich mir dann einen.
Wird aber noch etwas dauern.

VG

**Comment by Ceel84** [comment]
Würde es helfen wenn ich einen habe?

**Comment by Sickboy78** [comment]
Hallo @Ceel84 ,

danke für das Angebot, aber hilft nicht wirklich.
Der Futterautomat muss an meinem Hub angemeldet sein, damit ich mir die Kommunikation ansehen und nachbauen kann ...
Von daher musst du dich wohl Gedulden, bis meine Steuererstattung kommt. ;)

VG
Sickboy

**Comment by Sickboy78** [comment]
Hallo @Ceel84,

die Steuerrückzahlung hat für einen Futterautomat gereicht. :)
in der aktuellen Version 1.0.6 habe ich das erste Feature für den Automat implementiert:
Die Verzögerung vom Deckel kann eingestellt werden.

Welche Features wären denn noch interessant?

VG
Sickboy

**Comment by Phrixotrichus** [comment]
Interessant wäre noch der Restfutterstand und der kumulative "was wurde gefressen" Wert pro Tier. Ich nehme an, dass das schon in diesem Wust aus "history->weight"data sets mit drin ist und die Zuordnung in der App über die ID funktioniert, aber das fertig aufbereitet über den Adapter zu bekommen wäre natürlich toll.

**Comment by Sickboy78** [comment]
Restfutterstand, Futtertyp und Zielgewicht für Futterautomat, sowie heute gefressenes Futter, Anzahl und verbrachte Zeit am Futterautomat für haustier mit v1.0.8 hinzugefügt
