### ISSUE TITLE
History Bug is back?

### ISSUE THREAD

**Issue by MAR-L3Y** [Sickboy78/ioBroker.sureflap#49]
Hello Sebastian,
My history in iobroker got the last update around two hours ago. 
is it possible that the api got changed again or could it be that History bug you mentioned in a past post is back?
i couldn't tell excactly when this started but my girlfriend told me about one week ago that the status of our cats not changed in time.
this would make sense because of the significantly  delayed history.

Cheers
MedusA

**Comment by Sickboy78** [comment]
Hi MedusA,
I can reproduce the problem and it seems, there are some API changes as well.
I have to analyze whether this is the cause or just a coincidence.
But I'm afraid I probably won't find the time before Christmas.

Best Regards and Merry Christmas

**Comment by MAR-L3Y** [comment]
Its all good take as much time as you need.
hope you have a good holiday season
thanks again for your great work

**Comment by Sickboy78** [comment]
Hi MedusA,
I created a new version 1.2.3 which uses the new API.
Could you check, whether the problem still exists with the new version?
Happy New Year!
