### ISSUE TITLE
Feature: setPetLocking

### ISSUE THREAD

**Issue by mproper23** [Sickboy78/ioBroker.sureflap#8]
Hi,

would it be possible to add this one: 
setPetLocking.php

locking=[out|in] oder
lockingid=[2=out|3=in] oder
lockingLox=[0=out|1=in]

petname=[...]
Name des Haustiers muss zur Sicherheit immer mitgegeben werden 

as i read in loxone wiki it is possible to set a lock mode for every pet

**Comment by Sickboy78** [comment]
Hi,

should be possible.
I'll put it on my todo list.

Best Regards

**Comment by mproper23** [comment]
thank you

**Comment by Sickboy78** [comment]
Hi @mproper23 ,

version 1.0.6 now contains this feature, see household_name.hub_name.flap_name.assigned_pets.pet_name.control.type.
The prerequisite is that the cat is assigned to the flap in the app. Then it should appear in the sureflap adapter under assigned_pets and there you can specify the type: Outdoor or indoor cat.

Best regards
